### ISSUE TITLE
连不上tel

### ISSUE THREAD

**Issue by loks666** [uniStark/get-jobs-51job#1]
java.net.ConnectException: Failed to connect to api.telegram.org/162.125.18.133:443

一直报这个错误，在同一个类直接访问api.telegram.org的代码都没问题，使用bot.execute(sendMessageRequest);这个代码就说连不上，这是什么原因啊？

**Comment by loks666** [comment]
作者有没有联系方式能问问的？

**Comment by uniStark** [comment]
在src/main/java/utils/TelegramNotificationBot.java包内设置你BOT的TELEGRAM_API_TOKEN和CHAT_ID
